# Site settings
title: CraneoPhoto
email: cdhernandez007@gmail.com
topics: landscapes|birds|astrophotography
description: > # this means to ignore newlines until "baseurl:"
    A site for photography.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://craneophoto.com" # the base hostname & protocol for your site
github_username:  craneo007
flickr_username:  craneo007

# Build settings
markdown: kramdown
